# Generated by Django 3.2.7 on 2021-10-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picapp', '0007_remove_photo_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
