# Generated by Django 3.2.7 on 2021-10-05 09:48

from django.db import migrations, models
import imagekit.models.fields
import picapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('picapp', '0009_photo_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='photos/', validators=[picapp.models.Album.validate_image]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='photos/', validators=[picapp.models.Photo.validate_image]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
