# Generated by Django 3.2.7 on 2021-10-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picapp', '0011_auto_20211011_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Public Album'),
        ),
    ]
