# Generated by Django 2.2.10 on 2021-10-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picapp', '0005_auto_20210929_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
