# Generated by Django 2.2.10 on 2021-10-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picapp', '0006_auto_20211001_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_public',
        ),
    ]
