# Generated by Django 3.2.7 on 2021-10-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picapp', '0008_auto_20211001_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
